name: Release Packaging

on:
  push:
    branches:
      - main
      - 4.x
  workflow_dispatch:

jobs:
  release-packaging:
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.0

    name: ${{ matrix.preset }} Export
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows Export
            platform: windows
            output: Greeter.exe
            preset: Windows Desktop

          - platform: linux
            output: Greeter.x86_64
            preset: Linux/X11

          - platform: web
            output: index.html
            preset: Web

          # - platform: mac
          #   output: Greeter.zip
          #   preset: Mac OSX

    steps:
      - uses: actions/checkout@v3

      - name: Export Cursed Street
        uses: ./.github/actions/export-game
        with:
          output: ${{ matrix.platform }}/${{ matrix.output }}
          version: 0.1.0
          godot_version: 4.0
          preset: ${{ matrix.preset }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: CursedStreet-${{ matrix.platform }}-v${{ env.version }}
          path: build/${{ matrix.platform }}

      # Installing rsync is needed in order to deploy to GitHub Pages. Without it, the build will fail.
      - name: Install rsync
        if: ${{ matrix.platform == 'web' }}
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages
        if: ${{ matrix.platform == 'web' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
